[package]
name = "druid-shell-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid-shell = "0.7.0"
tracing-subscriber = "0.3.11"